//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym5DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreProducto
    {
        public string idProducto { get; set; }
        public string idCierre { get; set; }
        public string idNombreEmpresa { get; set; }
        public int cantidadCierre { get; set; }
        public string idCierreProducto { get; set; }
    
        public virtual Cierre Cierre { get; set; }
        public virtual LogEmpresa LogEmpresa { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
