//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym5DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogUsuario()
        {
            this.Cierres = new HashSet<Cierre>();
            this.InstructorGyms = new HashSet<InstructorGym>();
        }
    
        public string usuario { get; set; }
        public string pass { get; set; }
        public string idNombreEmpresa { get; set; }
        public string permiso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cierre> Cierres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorGym> InstructorGyms { get; set; }
        public virtual LogEmpresa LogEmpresa { get; set; }
    }
}
