//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym5DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaMedidasGym
    {
        public string idPersona { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<double> pecho { get; set; }
        public Nullable<double> espalda { get; set; }
        public Nullable<double> cintura { get; set; }
        public Nullable<double> cadera { get; set; }
        public Nullable<double> pierna { get; set; }
        public Nullable<double> pantorrilla { get; set; }
        public Nullable<double> brazo { get; set; }
        public Nullable<double> antebrazo { get; set; }
        public Nullable<double> triceps { get; set; }
        public Nullable<double> abdominal { get; set; }
        public Nullable<double> supraIliaco { get; set; }
        public Nullable<double> subscapular { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> estatura { get; set; }
        public Nullable<double> IMC { get; set; }
        public Nullable<double> porcentajeGrasa { get; set; }
        public string idMedida { get; set; }
    
        public virtual PersonaGym PersonaGym { get; set; }
    }
}
